### ISSUE TITLE
Excessive requirements.txt file

### ISSUE THREAD

**Issue by philippeitis** [lavishsaluja/ssTweet#6]
Is there any particular reason for all of the requirements in requirements.txt? The only ones that seem to be necessary are

```
google-auth==1.10.2
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
tweepy==3.8.0
requests==2.22.0
requests-oauthlib==1.3.0
```

**Comment by lavishsaluja** [comment]
I just created a python3 environment and installed dependencies when I used them and freezed all of them to a text file, they automatically got added. I thought they must be somehow linked if they were in `env` created.

**Comment by philippeitis** [comment]
That's possible, but the remaining files are dependencies for the files listed, so they don't particularly need to be included. Generally, I just add whatever I import in the code to the requirements.txt file to keep things simple.

**Comment by lavishsaluja** [comment]
Oh, OK. I'll try to run the code with only these requirements, mostly it'll work fine. I'm not sure myself, why freeze would add anything other than the dependencies that I installed with `pip install`

**Comment by lavishsaluja** [comment]
I'll remove unnecessary dependencies in `requirements.txt` once I finish a bunch of main tasks. I'll close this issue for now.
