### ISSUE TITLE
Not prompting user for Photos Access tokens everytime

### ISSUE THREAD

**Issue by lavishsaluja** [lavishsaluja/ssTweet#8]
I want to be able to store access tokens for different users and use refresh tokens to regenerate access tokens for their google photos account. I did try loading the access tokens from the credentials file with client token and client_secret token [Function in Authorization Class](https://github.com/lavishsaluja/ssTweet/blob/5578f627d6ac4ad531520a49ea6dd352bd3e7673/src/authorization_class.py#L40)

Hi, @philippeitis do you have any idea on how I can do this? Also, I want to avoid having the unsafe app error every time it prompts me for credentials, to verify an app with Google Developers, do I necessarily need a domain for the project?

**Comment by philippeitis** [comment]
You could take a look at https://github.com/googleapis/google-auth-library-python-oauthlib/blob/master/google_auth_oauthlib/tool/__main__.py#L80 for persisting files to disk.

**Comment by lavishsaluja** [comment]
Hi @philippeitis, sorry for the late reply. I tried doing this way but how do I get credentials for the argument also where does this use refresh tokens? Can you please explain in a bit detail on what will I be using?
